name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '16' ]
        # Kotlin needs access to java.util
        include:
          - java: '8'
            maven-opts: ''
          - java: '11'
            maven-opts: ''
          - java: '16'
            maven-opts: --add-opens java.base/java.util=ALL-UNNAMED
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: print Java version
      run: java -version
    - uses: actions/cache@v2.1.5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build
      env:
        MAVEN_OPTS: ${{ matrix.maven-opts }}
      run: mvn -B clean package --file pom.xml
